/*
  TABLAS : 43
  Maestras:           7
  Informativas:       3
  Operacionales:     13
  Transaccionales:    2
  Relacionales:       4
  Soporte/Auditoría:  4
  Históricas:         6
  Seguridad:          4
*/
/*
--******************************
-- SECCION DE BORRADO DE TABLAS
--****************************** 
DROP TABLE IF EXISTS LIKES_RESENAS;
DROP TABLE IF EXISTS TOKENS_RECUPERACION;
DROP TABLE IF EXISTS INTENTOS_LOGIN;
DROP TABLE IF EXISTS HISTORICO_PAGOS;
DROP TABLE IF EXISTS HISTORICO_PLAN_TURISTICO;
DROP TABLE IF EXISTS HISTORICO_USUARIOS_EMPRESA;
DROP TABLE IF EXISTS HISTORICO_EMPRESA;
DROP TABLE IF EXISTS HISTORICO_USUARIO;
DROP TABLE IF EXISTS HISTORICO_PERSONAS;
DROP TABLE IF EXISTS ACCESIBILIDAD_VIAJERO;
DROP TABLE IF EXISTS CONFIG_VIAJERO;
DROP TABLE IF EXISTS CONFIG_ADMIN;
DROP TABLE IF EXISTS CONFIG_EMPRESA;
DROP TABLE IF EXISTS FESTIVIDADES_SANTANDER;
DROP TABLE IF EXISTS PRODUCTOS_ARTESANALES;
DROP TABLE IF EXISTS AUDITORIA;
DROP TABLE IF EXISTS SOPORTE_VIAJERO;
DROP TABLE IF EXISTS MOTIVO_SOPORTE;
DROP TABLE IF EXISTS PAGOS_EPAYCO;
DROP TABLE IF EXISTS RESERVAS;
DROP TABLE IF EXISTS RESENAS_PLATAFORMA;
DROP TABLE IF EXISTS PLAN_COMPONENTES;
DROP TABLE IF EXISTS PLANES_TURISTICOS;
DROP TABLE IF EXISTS HOSPEDAJE_SERVICIOS;
DROP TABLE IF EXISTS HOSPEDAJE;
DROP TABLE IF EXISTS SERVICIOS_HOSPEDAJE;
DROP TABLE IF EXISTS TRANSPORTE;
DROP TABLE IF EXISTS TIPOS_DE_PLAN_TURISTICO;
DROP TABLE IF EXISTS PERSONAL_AUXILIAR;
DROP TABLE IF EXISTS CARGOS_PER_AUX;
DROP TABLE IF EXISTS HISTORIAL_CONTRASENAS_EMPRESA;
DROP TABLE IF EXISTS USUARIOS_EMPRESA;
DROP TABLE IF EXISTS HISTORIAL_CONTRASENAS_USUARIO;
DROP TABLE IF EXISTS ALERGIAS_VIAJERO;
DROP TABLE IF EXISTS USUARIOS_ECOMMERCE;
DROP TABLE IF EXISTS PERSONAS_ECOMMERCE;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS PERSONAS;
DROP TABLE IF EXISTS TIPOS_DOCUMENTOS;
DROP TABLE IF EXISTS ALERGIAS;
DROP TABLE IF EXISTS EMPRESAS;
DROP TABLE IF EXISTS CIUDADES;
DROP TABLE IF EXISTS DEPARTAMENTOS;
*/
-- *******************************
-- SECCIÓN DE CREACIÓN DE TABLAS *
-- *******************************

--******************************
-- MAESTRA
--******************************

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS
(
    ID_DPTO      VARCHAR(2)   NOT NULL CHECK(LENGTH(ID_DPTO) = 2 AND ID_DPTO ~ '^[0-9]{2}$'),
    NOM_DPTO     VARCHAR(18)  NOT NULL CHECK(LENGTH(NOM_DPTO) >= 3),
    PRIMARY KEY(ID_DPTO)
);

--******************************
-- MAESTRA
--******************************

CREATE TABLE IF NOT EXISTS CIUDADES
(
    ID_CIUDAD      VARCHAR(6)   NOT NULL CHECK(LENGTH(ID_CIUDAD) >= 5 AND ID_CIUDAD ~ '^[0-9A-Za-z]+$'),
    NOM_CIUDAD     VARCHAR(27)  NOT NULL CHECK(LENGTH(NOM_CIUDAD) >= 3),
    ID_DPTO        VARCHAR(2)   NOT NULL CHECK(LENGTH(ID_DPTO) = 2),
    PRIMARY KEY(ID_CIUDAD),
    FOREIGN KEY(ID_DPTO) REFERENCES DEPARTAMENTOS(ID_DPTO)
);

--**************
-- INFORMATIVA
--**************

CREATE TABLE IF NOT EXISTS EMPRESAS
(
    ID_EMPRESA              VARCHAR(10)   NOT NULL CHECK(LENGTH(ID_EMPRESA) = 10),
    NOM_EMPRESA             VARCHAR(50)   NOT NULL CHECK(LENGTH(NOM_EMPRESA) >= 2),
    EMAIL_INSTITU_EMPRESA   VARCHAR       NOT NULL CHECK(EMAIL_INSTITU_EMPRESA ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    NUM_CONTACTO_EMPRESA    VARCHAR(20)   NOT NULL CHECK(NUM_CONTACTO_EMPRESA ~ '^\+?[0-9]{7,15}$'),
    ID_CIUDAD               VARCHAR(6)    NOT NULL CHECK(LENGTH(ID_CIUDAD) >= 5),
    TIPO_SERVICIO           VARCHAR(20)   NOT NULL DEFAULT 'PLANES' CHECK (TIPO_SERVICIO IN ('HOSPEDAJE', 'PLANES', 'TRANSPORTE', 'PERSONAL_AUXILIAR')),
    PRIMARY KEY(ID_EMPRESA),
    FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD)
);

--******************************
-- MAESTRA
--******************************

CREATE TABLE IF NOT EXISTS TIPOS_DOCUMENTOS
(
    ID_TIPO_DOC    SMALLINT     NOT NULL CHECK(ID_TIPO_DOC > 0),
    NOM_TIPO_DOC   VARCHAR(21)  NOT NULL CHECK(LENGTH(NOM_TIPO_DOC) >= 2),
    PRIMARY KEY(ID_TIPO_DOC)
);

--******************************
-- MAESTRA
--******************************

CREATE TABLE IF NOT EXISTS ALERGIAS
(
    ID_ALERGIA    SMALLINT     NOT NULL CHECK(ID_ALERGIA >= 0),
    NOM_ALERGIA   VARCHAR(23)  NOT NULL CHECK(LENGTH(NOM_ALERGIA) >= 2),
    PRIMARY KEY(ID_ALERGIA)
);

--**************
-- INFORMATIVA
--**************

CREATE TABLE IF NOT EXISTS PERSONAS
(
    ID_PERSONA              VARCHAR(10)   NOT NULL CHECK(LENGTH(ID_PERSONA) >= 6 AND ID_PERSONA ~ '^[0-9]+$'),
    ID_TIPO_DOC             SMALLINT      NOT NULL CHECK(ID_TIPO_DOC > 0),
    NOM_PERSONA             VARCHAR(50)   NOT NULL CHECK(LENGTH(NOM_PERSONA) >= 2),
    APE_PERSONA             VARCHAR(50)   NOT NULL CHECK(LENGTH(APE_PERSONA) >= 2),
    NUM_CEL_PERSONA         VARCHAR(20)   NOT NULL CHECK(NUM_CEL_PERSONA ~ '^\+?[0-9]{7,15}$'),
    EMAIL_PERSONA           VARCHAR       NOT NULL CHECK(EMAIL_PERSONA ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    NECESIDAD_ACCESIBILIDAD VARCHAR(50)   NOT NULL DEFAULT 'NINGUNA' CHECK(NECESIDAD_ACCESIBILIDAD IN ('NINGUNA','MOVILIDAD','VISUAL','AUDITIVA','COGNITIVA','MULTIPLE')),
    FECHA_REGISTRO          TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_PERSONA),
    FOREIGN KEY(ID_TIPO_DOC) REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOC)
);

--****************
-- OPERACIONAL
--****************

CREATE TABLE IF NOT EXISTS USUARIOS
(
    ID_PERSONA    VARCHAR(10)  NOT NULL CHECK(LENGTH(ID_PERSONA) >= 6),
    ROL           VARCHAR(10)  NOT NULL DEFAULT 'viajero' CHECK(ROL IN ('viajero','admin')),
    EMAIL_LOGIN   VARCHAR      NOT NULL UNIQUE CHECK(EMAIL_LOGIN ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONTRASENA    VARCHAR(64)  NOT NULL CHECK(LENGTH(CONTRASENA) = 64 AND CONTRASENA ~ '^[a-f0-9]{64}$'),
    ESTADO        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO' CHECK(ESTADO IN ('ACTIVO','INACTIVO')),
    PRIMARY KEY(ID_PERSONA),
    FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA)
);

--**************
-- INFORMATIVA
--**************

CREATE TABLE IF NOT EXISTS PERSONAS_ECOMMERCE
(
    ID_PERSONA_ECOMMERCE        VARCHAR(10)   NOT NULL CHECK(LENGTH(ID_PERSONA_ECOMMERCE) >= 6 AND ID_PERSONA_ECOMMERCE ~ '^[0-9]+$'),
    ID_TIPO_DOC                 SMALLINT      NOT NULL CHECK(ID_TIPO_DOC > 0),
    NOM_PERSONA_ECOMMERCE       VARCHAR(50)   NOT NULL CHECK(LENGTH(NOM_PERSONA_ECOMMERCE) >= 2),
    APE_PERSONA_ECOMMERCE       VARCHAR(50)   NOT NULL CHECK(LENGTH(APE_PERSONA_ECOMMERCE) >= 2),
    NUM_CEL_PERSONA_ECOMMERCE   VARCHAR(20)   NOT NULL CHECK(NUM_CEL_PERSONA_ECOMMERCE ~ '^\+?[0-9]{7,15}$'),
    EMAIL_PERSONA_ECOMMERCE     VARCHAR       NOT NULL CHECK(EMAIL_PERSONA_ECOMMERCE ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    FECHA_REGISTRO          TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_PERSONA_ECOMMERCE),
    FOREIGN KEY(ID_TIPO_DOC) REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOC)
);

--****************
-- OPERACIONAL
--****************

CREATE TABLE IF NOT EXISTS USUARIOS_ECOMMERCE
(
    ID_PERSONA_ECOMMERCE        VARCHAR(10)  NOT NULL CHECK(LENGTH(ID_PERSONA_ECOMMERCE) >= 6),
    EMAIL_LOGIN   VARCHAR      NOT NULL UNIQUE CHECK(EMAIL_LOGIN ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONTRASENA    VARCHAR(64)  NOT NULL CHECK(LENGTH(CONTRASENA) = 64 AND CONTRASENA ~ '^[a-f0-9]{64}$'),
    ESTADO        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO' CHECK(ESTADO IN ('ACTIVO','INACTIVO','PENDIENTE')),
    PRIMARY KEY(ID_PERSONA_ECOMMERCE),
    FOREIGN KEY(ID_PERSONA_ECOMMERCE) REFERENCES PERSONAS_ECOMMERCE(ID_PERSONA_ECOMMERCE)
);

--******************************
-- SEGURIDAD
--******************************

CREATE TABLE IF NOT EXISTS HISTORIAL_CONTRASENAS_USUARIO 
(
    ID_HISTORIAL    SERIAL,
    ID_USUARIO      VARCHAR(10) NOT NULL CHECK(LENGTH(ID_USUARIO) >= 6 AND ID_USUARIO ~ '^[0-9]+$'),
    CONTRASENA_HASH VARCHAR(64) NOT NULL CHECK(LENGTH(CONTRASENA_HASH) = 64 AND CONTRASENA_HASH ~ '^[a-f0-9]{64}$'),
    FECHA_CAMBIO    TIMESTAMP   NOT NULL DEFAULT NOW(),
	PRIMARY KEY (ID_HISTORIAL),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_PERSONA)
);


--***************
-- RELACIONAL
--***************

CREATE TABLE IF NOT EXISTS ALERGIAS_VIAJERO
(
    ID_USUARIO   VARCHAR(10) NOT NULL CHECK(LENGTH(ID_USUARIO) >= 6 AND ID_USUARIO ~ '^[0-9]+$'),
    ID_ALERGIA   SMALLINT    NOT NULL CHECK(ID_ALERGIA >= 0),
    PRIMARY KEY (ID_USUARIO, ID_ALERGIA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_PERSONA), 
    FOREIGN KEY (ID_ALERGIA) REFERENCES ALERGIAS(ID_ALERGIA)
);

--****************
-- OPERACIONAL
--****************

CREATE TABLE IF NOT EXISTS USUARIOS_EMPRESA
(
    ID_EMPRESA      VARCHAR(10)  NOT NULL CHECK(LENGTH(ID_EMPRESA) = 10 AND ID_EMPRESA ~ '^[0-9]+$'),
    EMAIL_LOGIN     VARCHAR      NOT NULL UNIQUE CHECK(EMAIL_LOGIN ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONTRASENA      VARCHAR(64)  NOT NULL CHECK(LENGTH(CONTRASENA) = 64 AND CONTRASENA ~ '^[a-f0-9]{64}$'),
    ESTADO          VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO' CHECK(ESTADO IN ('ACTIVO','INACTIVO','PENDIENTE')),
    FECHA_REGISTRO  TIMESTAMP    NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_EMPRESA),
    FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA)
);


--******************************
-- SEGURIDAD
--******************************

CREATE TABLE IF NOT EXISTS HISTORIAL_CONTRASENAS_EMPRESA 
(
    ID_HISTORIAL    SERIAL,
    ID_EMPRESA      VARCHAR(10) NOT NULL CHECK(LENGTH(ID_EMPRESA) = 10 AND ID_EMPRESA ~ '^[0-9]+$'),
    CONTRASENA_HASH VARCHAR(64) NOT NULL CHECK(LENGTH(CONTRASENA_HASH) = 64 AND CONTRASENA_HASH ~ '^[a-f0-9]{64}$'),
    FECHA_CAMBIO    TIMESTAMP   NOT NULL DEFAULT NOW(),
	PRIMARY KEY(ID_HISTORIAL),
    FOREIGN KEY (ID_EMPRESA) REFERENCES USUARIOS_EMPRESA(ID_EMPRESA)
);

--******************************
-- MAESTRA
--******************************

CREATE TABLE IF NOT EXISTS CARGOS_PER_AUX
(
    ID_CARGO_AUX   DECIMAL(1,0)  NOT NULL CHECK(ID_CARGO_AUX > 0),
    NOM_CARGO      VARCHAR       NOT NULL CHECK(LENGTH(NOM_CARGO) >= 3),
    SALARIO_CARGO  DECIMAL(10,0) NOT NULL CHECK(SALARIO_CARGO >= 0),
    PRIMARY KEY(ID_CARGO_AUX)
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS PERSONAL_AUXILIAR
(
    ID_PERSONAL_AUXILIAR   SERIAL        NOT NULL,
    ID_EMPRESA             VARCHAR(10)   NOT NULL CHECK(LENGTH(ID_EMPRESA) = 10),
    ID_CARGO_AUX           DECIMAL(1,0)  NOT NULL CHECK(ID_CARGO_AUX > 0),
    NOMBRE_PROFESIONAL     VARCHAR(100)  NOT NULL CHECK(LENGTH(NOMBRE_PROFESIONAL) >= 3),
    DISPONIBILIDAD         VARCHAR(100)  NOT NULL CHECK(LENGTH(DISPONIBILIDAD) >= 3),
    EXPERIENCIA            VARCHAR(200)  NOT NULL CHECK(LENGTH(EXPERIENCIA) >= 3),
    ESPECIALIDAD           TEXT          NOT NULL CHECK(LENGTH(ESPECIALIDAD) >= 3),
    ACCESIBILIDAD          TEXT          CHECK(ACCESIBILIDAD IS NULL OR LENGTH(ACCESIBILIDAD) >= 3),
    ID_CIUDAD              VARCHAR(6)    NOT NULL CHECK(LENGTH(ID_CIUDAD) >= 5),
    TARIFA                 DECIMAL(10,0) NOT NULL CHECK(TARIFA > 0),
    DISPONIBLE             BOOLEAN       NOT NULL DEFAULT TRUE,
    IMG_URL                VARCHAR(255)  CHECK(IMG_URL IS NULL OR LENGTH(IMG_URL) >= 5),
    FECHA_CREACION         TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_PERSONAL_AUXILIAR),
    FOREIGN KEY(ID_EMPRESA)   REFERENCES EMPRESAS(ID_EMPRESA),
    FOREIGN KEY(ID_CARGO_AUX) REFERENCES CARGOS_PER_AUX(ID_CARGO_AUX),
    FOREIGN KEY(ID_CIUDAD)    REFERENCES CIUDADES(ID_CIUDAD)
);

--******************************
-- MAESTRA
--******************************

CREATE TABLE IF NOT EXISTS TIPOS_DE_PLAN_TURISTICO
(
    ID_TIPO_PLAN    SMALLINT     NOT NULL CHECK(ID_TIPO_PLAN > 0),
    NOM_TIPO_PLAN   VARCHAR(28)  NOT NULL CHECK(LENGTH(NOM_TIPO_PLAN) >= 3),
    PRIMARY KEY(ID_TIPO_PLAN)
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS TRANSPORTE
(
    ID_TRANSPORTE       SERIAL          NOT NULL,
    ID_EMPRESA          VARCHAR(10)     NOT NULL CHECK(LENGTH(ID_EMPRESA) = 10),
    ORIGEN              VARCHAR(100)    NOT NULL CHECK(LENGTH(ORIGEN) >= 3),
    DESTINO             VARCHAR(100)    NOT NULL CHECK(LENGTH(DESTINO) >= 3),
    FECHA_SALIDA        DATE            NOT NULL CHECK(FECHA_SALIDA >= CURRENT_DATE),
    HORA_SALIDA         TIME            NOT NULL,
    PRECIO              DECIMAL(12,0)   NOT NULL CHECK(PRECIO > 0),
    DISPONIBILIDAD      BOOLEAN         NOT NULL DEFAULT TRUE,
    DESCRIPCION         TEXT            CHECK(DESCRIPCION IS NULL OR LENGTH(DESCRIPCION) >= 5),
    IMG_URL             VARCHAR(255)    CHECK(IMG_URL IS NULL OR LENGTH(IMG_URL) >= 5),
    FECHA_CREACION      TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_TRANSPORTE),
    FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA)
);

--******************************
-- MAESTRA
--******************************

CREATE TABLE IF NOT EXISTS SERVICIOS_HOSPEDAJE (
    ID_SERVICIO       SERIAL        NOT NULL,
    NOMBRE_SERVICIO   VARCHAR(100)  NOT NULL UNIQUE CHECK(LENGTH(NOMBRE_SERVICIO) >= 3),
    ACTIVO            BOOLEAN       NOT NULL DEFAULT TRUE,
    FECHA_CREACION    TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_SERVICIO)
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS HOSPEDAJE
(
    ID_HOSPEDAJE      SERIAL          NOT NULL,  
    ID_EMPRESA        VARCHAR(10)     NOT NULL CHECK(LENGTH(ID_EMPRESA) = 10),
    NOM_HOSPEDAJE     VARCHAR(100)    NOT NULL CHECK(LENGTH(NOM_HOSPEDAJE) >= 3),
    TIPO_HOSPEDAJE    VARCHAR(30)     NOT NULL CHECK(TIPO_HOSPEDAJE IN ('Hotel','Hotel Boutique','Finca','Cabaña','Hostal','Apartamento','Glamping')),
    ID_CIUDAD         VARCHAR(6)      NOT NULL CHECK(LENGTH(ID_CIUDAD) >= 5),
    DESCRIPCION       TEXT            CHECK(DESCRIPCION IS NULL OR LENGTH(DESCRIPCION) >= 5),
    PRECIO_NOCHE      DECIMAL(12,0)   NOT NULL CHECK(PRECIO_NOCHE > 0),
    ACCESIBILIDAD     VARCHAR(200)    NOT NULL CHECK(LENGTH(ACCESIBILIDAD) >= 3),
    CAPACIDAD_MAX     DECIMAL(3,0)    NOT NULL CHECK(CAPACIDAD_MAX > 0),
    IMG_URL           VARCHAR(255)    CHECK(IMG_URL IS NULL OR LENGTH(IMG_URL) >= 5),
    DISPONIBILIDAD    BOOLEAN         NOT NULL DEFAULT TRUE,
    FECHA_CREACION    TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_HOSPEDAJE),
    FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA),
    FOREIGN KEY(ID_CIUDAD)  REFERENCES CIUDADES(ID_CIUDAD)
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS PLANES_TURISTICOS
(
    ID_PLAN_TURISTICO        SERIAL        NOT NULL,  
    NOM_PLAN_TURISTICO       VARCHAR(100)  NOT NULL CHECK(LENGTH(NOM_PLAN_TURISTICO) >= 3),
    DURACION                 VARCHAR(50)   NOT NULL CHECK(LENGTH(DURACION) >= 2),
    DESCRIPCION              TEXT            CHECK(DESCRIPCION IS NULL OR LENGTH(DESCRIPCION) >= 5),
    INCLUYE                  TEXT            NOT NULL CHECK(LENGTH(INCLUYE) >= 3),
    ID_TIPO_PLAN             SMALLINT        NOT NULL CHECK(ID_TIPO_PLAN > 0),
    PRECIO_PLAN              DECIMAL(12,0)   NOT NULL CHECK(PRECIO_PLAN > 0),
    ACCESIBILIDAD            VARCHAR(200)    NOT NULL CHECK(LENGTH(ACCESIBILIDAD) >= 3),
    DISPONIBILIDAD           BOOLEAN         NOT NULL DEFAULT TRUE,
    ID_EMPRESA               VARCHAR(10)     NOT NULL CHECK(LENGTH(ID_EMPRESA) = 10),
    ID_CIUDAD                VARCHAR(6)      NOT NULL CHECK(LENGTH(ID_CIUDAD) >= 5),
    IMG_URL                  VARCHAR(255)    CHECK(IMG_URL IS NULL OR LENGTH(IMG_URL) >= 5),
    FECHA_CREACION           TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_PLAN_TURISTICO),
    FOREIGN KEY(ID_TIPO_PLAN) REFERENCES TIPOS_DE_PLAN_TURISTICO(ID_TIPO_PLAN),
    FOREIGN KEY(ID_EMPRESA)   REFERENCES EMPRESAS(ID_EMPRESA),
    FOREIGN KEY(ID_CIUDAD)    REFERENCES CIUDADES(ID_CIUDAD)
);

--******************************
-- RELACIONAL
--******************************

CREATE TABLE IF NOT EXISTS HOSPEDAJE_SERVICIOS (
    ID_HOSPEDAJE   INT NOT NULL,
    ID_SERVICIO    INT NOT NULL,
    PRIMARY KEY (ID_HOSPEDAJE, ID_SERVICIO),
    FOREIGN KEY (ID_HOSPEDAJE) REFERENCES HOSPEDAJE(ID_HOSPEDAJE) ON DELETE CASCADE,
    FOREIGN KEY (ID_SERVICIO)  REFERENCES SERVICIOS_HOSPEDAJE(ID_SERVICIO) ON DELETE CASCADE
);

--******************************
-- RELACIONAL
--******************************

CREATE TABLE IF NOT EXISTS PLAN_COMPONENTES
(
    ID_PLAN_COMP         SERIAL       NOT NULL,
    ID_PLAN_TURISTICO    INT          NOT NULL CHECK(ID_PLAN_TURISTICO > 0),
    TIPO_COMPONENTE      VARCHAR(20)  NOT NULL CHECK(TIPO_COMPONENTE IN ('HOSPEDAJE', 'PERSONAL_AUXILIAR', 'TRANSPORTE')),
    ID_HOSPEDAJE         INT          CHECK(ID_HOSPEDAJE IS NULL OR ID_HOSPEDAJE > 0),
    ID_PERSONAL_AUXILIAR INT          CHECK(ID_PERSONAL_AUXILIAR IS NULL OR ID_PERSONAL_AUXILIAR > 0),
    NOTAS                VARCHAR(200) CHECK(NOTAS IS NULL OR LENGTH(NOTAS) >= 3),
    PRIMARY KEY(ID_PLAN_COMP),
    FOREIGN KEY(ID_PLAN_TURISTICO)    REFERENCES PLANES_TURISTICOS(ID_PLAN_TURISTICO),
    FOREIGN KEY(ID_HOSPEDAJE)         REFERENCES HOSPEDAJE(ID_HOSPEDAJE),
    FOREIGN KEY(ID_PERSONAL_AUXILIAR) REFERENCES PERSONAL_AUXILIAR(ID_PERSONAL_AUXILIAR)
);

--******************************
-- SOPORTE
--******************************

CREATE TABLE IF NOT EXISTS RESENAS_PLATAFORMA 
(
    ID_RESENA          SERIAL,
    ID_PERSONA         VARCHAR(10)   NOT NULL,
    PUNTUACION         SMALLINT      NOT NULL CHECK (PUNTUACION BETWEEN 1 AND 5),
    COMENTARIO         TEXT          NOT NULL CHECK (LENGTH(COMENTARIO) >= 10),
    FECHA_CREACION     TIMESTAMP     NOT NULL DEFAULT NOW(),
	PRIMARY KEY(ID_RESENA),
    FOREIGN KEY(ID_PERSONA) 		 REFERENCES PERSONAS(ID_PERSONA)
);

--******************************
-- TRANSACCIONAL
--******************************

CREATE TABLE IF NOT EXISTS RESERVAS
(
    ID_RESERVA              SERIAL          NOT NULL,
    ID_USUARIO              VARCHAR(10)     NOT NULL CHECK(LENGTH(ID_USUARIO) >= 6),
    FECHA_RESERVA           DATE            NOT NULL DEFAULT CURRENT_DATE CHECK(FECHA_RESERVA >= '2020-01-01'),
    MENORES                 BOOLEAN         NOT NULL,
    NUM_MENORES             DECIMAL(2,0)    NOT NULL DEFAULT 0 CHECK(NUM_MENORES >= 0),
    TIPO_SERVICIO           VARCHAR(20)     NOT NULL DEFAULT 'PLAN' CHECK(TIPO_SERVICIO IN ('PLAN','HOSPEDAJE','TRANSPORTE','PERSONAL_AUXILIAR')),
    ID_PLAN_TURISTICO       INT             CHECK(ID_PLAN_TURISTICO IS NULL OR ID_PLAN_TURISTICO > 0),
    ID_HOSPEDAJE            INT             CHECK(ID_HOSPEDAJE IS NULL OR ID_HOSPEDAJE > 0),
    ID_TRANSPORTE           INT             CHECK(ID_TRANSPORTE IS NULL OR ID_TRANSPORTE > 0),
    ID_PERSONAL_AUXILIAR    INT             CHECK(ID_PERSONAL_AUXILIAR IS NULL OR ID_PERSONAL_AUXILIAR > 0),
    NUM_USUARIOS            DECIMAL(2,0)    NOT NULL CHECK(NUM_USUARIOS > 0),
    ESTADO                  VARCHAR(12)     NOT NULL DEFAULT 'ACTIVA' CHECK(ESTADO IN ('ACTIVA','EN_CURSO','COMPLETADA','CANCELADA')),
    ESTADO_PAGO             VARCHAR(20)     NOT NULL DEFAULT 'Pendiente' CHECK(ESTADO_PAGO IN ('Aceptada','Pendiente','Rechazada','Fallida')),
    FECHA_CREACION          TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_RESERVA),
    FOREIGN KEY(ID_USUARIO)           REFERENCES USUARIOS(ID_PERSONA),
    FOREIGN KEY(ID_PLAN_TURISTICO)    REFERENCES PLANES_TURISTICOS(ID_PLAN_TURISTICO),
    FOREIGN KEY(ID_HOSPEDAJE)         REFERENCES HOSPEDAJE(ID_HOSPEDAJE),
    FOREIGN KEY(ID_TRANSPORTE)        REFERENCES TRANSPORTE(ID_TRANSPORTE),
    FOREIGN KEY(ID_PERSONAL_AUXILIAR) REFERENCES PERSONAL_AUXILIAR(ID_PERSONAL_AUXILIAR)
);

--******************************
-- TRANSACCIONAL
--******************************

CREATE TABLE IF NOT EXISTS PAGOS_EPAYCO
(
    ID_PAGO                 SERIAL          NOT NULL,
    ID_RESERVA              INT             NOT NULL CHECK(ID_RESERVA > 0),
    EPAYCO_REF_PAYCO        VARCHAR(100)    NOT NULL UNIQUE CHECK(LENGTH(EPAYCO_REF_PAYCO) >= 1),
    EPAYCO_TRANSACTION_ID   VARCHAR(100)    NOT NULL UNIQUE CHECK(LENGTH(EPAYCO_TRANSACTION_ID) >= 1),
    REFERENCIA              VARCHAR(100)    NOT NULL UNIQUE CHECK(LENGTH(REFERENCIA) >= 5),
    MONTO_PESOS             DECIMAL(12,0)   NOT NULL CHECK(MONTO_PESOS > 0),
    MONEDA                  CHAR(3)         NOT NULL DEFAULT 'COP' CHECK(MONEDA IN ('COP','USD','EUR')),
    ESTADO_EPAYCO           VARCHAR(20)     NOT NULL CHECK(ESTADO_EPAYCO IN ('Aceptada','Pendiente','Rechazada','Fallida')),
    METODO_PAGO             VARCHAR(50),
    FECHA_CREACION          TIMESTAMP       NOT NULL DEFAULT NOW(),
    FECHA_ACTUALIZACION     TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_PAGO),
    FOREIGN KEY(ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA)
);

--******************************
-- SOPORTE
--******************************

CREATE TABLE IF NOT EXISTS MOTIVO_SOPORTE 
(
    ID_MOTIVO         SERIAL        NOT NULL,
    NOMBRE_MOTIVO     VARCHAR(100)  NOT NULL UNIQUE CHECK(LENGTH(NOMBRE_MOTIVO) >= 5),
    CATEGORIA         VARCHAR(50)   NOT NULL, -- Ej: 'Facturación', 'Reserva', 'Técnico', 'Queja'
    ACTIVO            BOOLEAN       NOT NULL DEFAULT TRUE,
    FECHA_CREACION    TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_MOTIVO)
);

--******************************
-- SOPORTE
--******************************

CREATE TABLE IF NOT EXISTS SOPORTE_VIAJERO
(
    ID_SOPORTE        SERIAL        NOT NULL,
    ID_USUARIO        VARCHAR(10)   NOT NULL CHECK(LENGTH(ID_USUARIO) >= 6),
    ID_EMPRESA        VARCHAR(10)   NOT NULL CHECK(LENGTH(ID_EMPRESA) = 10),
    ID_RESERVA        INT           CHECK(ID_RESERVA IS NULL OR ID_RESERVA > 0),
    FECHA_SOLICITUD   TIMESTAMP     NOT NULL DEFAULT NOW(),
    ID_MOTIVO         INT           NOT NULL, 
    DESCRIPCION       TEXT          NOT NULL CHECK(LENGTH(DESCRIPCION) >= 5), 
    PRIORIDAD         VARCHAR(10)   NOT NULL DEFAULT 'MEDIA' CHECK(PRIORIDAD IN ('ALTA','MEDIA','BAJA')),
    ESTADO            VARCHAR(12)   NOT NULL DEFAULT 'ABIERTA' CHECK(ESTADO IN ('ABIERTA','EN_PROCESO','RESUELTA','CERRADA')),
    RESPUESTA_EMPRESA VARCHAR(300)  CHECK(RESPUESTA_EMPRESA IS NULL OR LENGTH(RESPUESTA_EMPRESA) >= 5),
    FECHA_CIERRE      TIMESTAMP     CHECK(FECHA_CIERRE IS NULL OR FECHA_CIERRE >= FECHA_SOLICITUD),
    
    PRIMARY KEY(ID_SOPORTE),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_PERSONA), 
    FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA),
    FOREIGN KEY(ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA),
    FOREIGN KEY(ID_MOTIVO)  REFERENCES MOTIVO_SOPORTE(ID_MOTIVO)
);

--******************************
-- AUDITORIA
--******************************

CREATE TABLE IF NOT EXISTS AUDITORIA
(
    ID_AUDITORIA       SERIAL        NOT NULL,
    FECHA_HORA         TIMESTAMP 	 WITHOUT TIME ZONE NOT NULL,
    ID_USUARIO         VARCHAR(10)   CHECK(ID_USUARIO IS NULL OR (LENGTH(ID_USUARIO) >= 6 AND ID_USUARIO ~ '^[0-9]+$')),
    NOM_OPERACION      VARCHAR(10)   NOT NULL,
	REG_ANTERIOR	   JSONB         NULL,
	REG_NUEVO		   JSONB         NULL,
    TABLA_AFECTADA     VARCHAR(30)   CHECK(TABLA_AFECTADA IS NULL OR LENGTH(TABLA_AFECTADA) >= 3),
    PRIMARY KEY(ID_AUDITORIA),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_PERSONA)
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS PRODUCTOS_ARTESANALES
(
    ID_PRODUCTO             SERIAL          NOT NULL,
    NOM_PRODUCTO            VARCHAR(100)    NOT NULL CHECK(LENGTH(NOM_PRODUCTO) >= 3),
    PROVEEDOR               VARCHAR(80)     NOT NULL CHECK(LENGTH(PROVEEDOR) >= 3),
    CATEGORIA               VARCHAR(20)     NOT NULL CHECK(CATEGORIA IN ('talleres','bisuteria','alfareria')),
    PRECIO_COP              DECIMAL(10,0)   NOT NULL CHECK(PRECIO_COP > 0),
    ID_CIUDAD               VARCHAR(6)      NOT NULL CHECK(LENGTH(ID_CIUDAD) >= 5),
    NUM_CONTACTO            VARCHAR(20)     NOT NULL CHECK(NUM_CONTACTO ~ '^\+?[0-9 ]{7,20}$'),
    DESCRIPCION             TEXT            NOT NULL CHECK(LENGTH(DESCRIPCION) >= 10),
    IMG_URL                 VARCHAR(255)    CHECK(IMG_URL IS NULL OR LENGTH(IMG_URL) >= 5),
    ID_PERSONA_ECOMMERCE    VARCHAR(10),
    FECHA_REGISTRO          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_PRODUCTO),
    FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD),
    FOREIGN KEY(ID_PERSONA_ECOMMERCE) REFERENCES PERSONAS_ECOMMERCE(ID_PERSONA_ECOMMERCE)
);


--*****************
-- INFORMATIVA
--*****************

CREATE TABLE IF NOT EXISTS FESTIVIDADES_SANTANDER
(
    ID_FESTIVIDAD   VARCHAR(40)     NOT NULL CHECK(LENGTH(ID_FESTIVIDAD) >= 3),
    FECHA_CLAVE     CHAR(5)         NOT NULL CHECK(FECHA_CLAVE ~ '^\d{2}-\d{2}$'),
    SUBTITULO       VARCHAR(80)     NOT NULL CHECK(LENGTH(SUBTITULO) >= 3),
    TITULO          VARCHAR(120)    NOT NULL CHECK(LENGTH(TITULO) >= 3),
    FRASE           VARCHAR(200)    NOT NULL CHECK(LENGTH(FRASE) >= 5),
    EMOJI           VARCHAR(10)     NOT NULL CHECK(LENGTH(EMOJI) >= 1),
    COLOR_1         CHAR(7)         NOT NULL CHECK(COLOR_1 ~ '^#[0-9A-Fa-f]{6}$'),
    COLOR_2         CHAR(7)         NOT NULL CHECK(COLOR_2 ~ '^#[0-9A-Fa-f]{6}$'),
    COLOR_3         CHAR(7)         NOT NULL CHECK(COLOR_3 ~ '^#[0-9A-Fa-f]{6}$'),
    BG_CARD         CHAR(7)         NOT NULL CHECK(BG_CARD ~ '^#[0-9A-Fa-f]{6}$'),
    TIPO            VARCHAR(10)     NOT NULL DEFAULT 'REGIONAL' CHECK(TIPO IN ('REGIONAL','NACIONAL')),
    ID_CIUDAD       VARCHAR(6)      NULL CHECK(ID_CIUDAD IS NULL OR LENGTH(ID_CIUDAD) >= 5),
    PRIMARY KEY(ID_FESTIVIDAD),
    FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD)
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS CONFIG_EMPRESA
(
    ID_CONFIG                   SERIAL          NOT NULL,
    ID_EMPRESA                  VARCHAR(10)     NOT NULL UNIQUE CHECK(LENGTH(ID_EMPRESA) = 10),
    NOTIF_NUEVAS_RESERVAS       BOOLEAN         NOT NULL DEFAULT TRUE,
    NOTIF_CANCELACIONES         BOOLEAN         NOT NULL DEFAULT TRUE,
    NOTIF_BOLETIN               BOOLEAN         NOT NULL DEFAULT FALSE,
    TEMA_OSCURO                 BOOLEAN         NOT NULL DEFAULT FALSE,
    FECHA_ACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_CONFIG),
    FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA)
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS CONFIG_ADMIN
(
    ID_CONFIG                  SERIAL        NOT NULL,
    ID_USUARIO                 VARCHAR(10)   NOT NULL UNIQUE CHECK(LENGTH(ID_USUARIO) >= 6),
    NOTIF_NUEVAS_RESERVAS      BOOLEAN       NOT NULL DEFAULT TRUE,
    NOTIF_CANCELACIONES        BOOLEAN       NOT NULL DEFAULT TRUE,
    NOTIF_NUEVAS_RESENAS       BOOLEAN       NOT NULL DEFAULT TRUE,
    NOTIF_BOLETIN_MENSUAL      BOOLEAN       NOT NULL DEFAULT FALSE,
    TEMA_OSCURO                BOOLEAN       NOT NULL DEFAULT FALSE,
    FECHA_ACTUALIZACION        TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_CONFIG),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_PERSONA)
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS CONFIG_VIAJERO
(
    ID_CONFIG                SERIAL        NOT NULL,
    ID_USUARIO               VARCHAR(10)   NOT NULL UNIQUE CHECK(LENGTH(ID_USUARIO) >= 6),
    NOTIF_CONFIRMACIONES     BOOLEAN       NOT NULL DEFAULT TRUE,
    NOTIF_OFERTAS            BOOLEAN       NOT NULL DEFAULT TRUE,
    NOTIF_RECORDATORIOS      BOOLEAN       NOT NULL DEFAULT TRUE,
    TEMA_OSCURO              BOOLEAN       NOT NULL DEFAULT FALSE,
    FECHA_ACTUALIZACION      TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_CONFIG),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_PERSONA) 
);

--******************************
-- OPERACIONAL
--******************************

CREATE TABLE IF NOT EXISTS ACCESIBILIDAD_VIAJERO
(
    ID_ACCESIBILIDAD   SERIAL        NOT NULL,
    ID_USUARIO         VARCHAR(10)   NOT NULL CHECK(LENGTH(ID_USUARIO) >= 6),
    TIPO               VARCHAR(20)   NOT NULL CHECK(TIPO IN ('MOVILIDAD','VISUAL','AUDITIVA','COGNITIVA','MULTIPLE')),
    DESCRIPCION        VARCHAR(100)  NOT NULL CHECK(LENGTH(DESCRIPCION) >= 3),
    FECHA_REGISTRO     TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_ACCESIBILIDAD),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_PERSONA)
);

--******************************
-- HISTORICA
--******************************

CREATE TABLE IF NOT EXISTS HISTORICO_PERSONAS 
(
    ID_HIST_PERSONA 		SERIAL 			NOT NULL,
    ID_PERSONA_ORIGINAL 	VARCHAR(10) 	NOT NULL,
    DATOS_SNAPSHOT 			JSONB,
    ACCION 					VARCHAR(10),
    FECHA_MODIFICACION 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
    USUARIO_RESPONSABLE 	VARCHAR(100) 	DEFAULT CURRENT_USER,
	PRIMARY KEY(ID_HIST_PERSONA)
);

--******************************
-- HISTORICA
--******************************

CREATE TABLE IF NOT EXISTS HISTORICO_USUARIO 
(
    ID_HIST_USUARIO 		SERIAL,
    ID_USUARIO_ORIGINAL 	VARCHAR(10) NOT NULL,
    DATOS_SNAPSHOT 			JSONB,
    ACCION 					VARCHAR(10),
    FECHA_MODIFICACION 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
    USUARIO_RESPONSABLE 	VARCHAR(100) 	DEFAULT CURRENT_USER,
	PRIMARY KEY(ID_HIST_USUARIO)
);

--******************************
-- HISTORICA
--******************************

CREATE TABLE IF NOT EXISTS HISTORICO_EMPRESA 
(
    ID_HIST_EMPRESA 		SERIAL,
    ID_EMPRESA_ORIGINAL 	VARCHAR(10) NOT NULL,
    DATOS_SNAPSHOT 			JSONB,
    ACCION 					VARCHAR(10),
    FECHA_MODIFICACION 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
    USUARIO_RESPONSABLE 	VARCHAR(100) 	DEFAULT CURRENT_USER,
	PRIMARY KEY(ID_HIST_EMPRESA)
);

--******************************
-- HISTORICA
--******************************

CREATE TABLE IF NOT EXISTS HISTORICO_USUARIOS_EMPRESA 
(
    ID_HIST_USU_EMP 		SERIAL,
    ID_EMPRESA_ORIGINAL 	VARCHAR(10) NOT NULL,
    DATOS_SNAPSHOT 			JSONB,
    ACCION 					VARCHAR(10),
    FECHA_MODIFICACION 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
    USUARIO_RESPONSABLE 	VARCHAR(100) 	DEFAULT CURRENT_USER,
	PRIMARY KEY(ID_HIST_USU_EMP)
);

--******************************
-- HISTORICA
--******************************

CREATE TABLE IF NOT EXISTS HISTORICO_PLAN_TURISTICO (
    id_hist_plan SERIAL PRIMARY KEY,
    id_plan_original INT NOT NULL,
    datos_snapshot JSONB,
    accion VARCHAR(10),
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_responsable VARCHAR(100)  DEFAULT CURRENT_USER
);

--******************************
-- HISTORICA
--******************************

CREATE TABLE IF NOT EXISTS HISTORICO_PAGOS (
    id_hist_pago SERIAL PRIMARY KEY,
    id_pago_original INT NOT NULL,
    datos_snapshot JSONB,
    accion VARCHAR(10),
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_responsable VARCHAR(100)  DEFAULT CURRENT_USER
);


--******************************
-- SEGURIDAD
--******************************

CREATE TABLE IF NOT EXISTS INTENTOS_LOGIN
(
    ID_INTENTO      SERIAL          NOT NULL,
    EMAIL           VARCHAR         NOT NULL CHECK(EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    IP_ORIGEN       VARCHAR(45)     NOT NULL CHECK(IP_ORIGEN ~ '^(\d{1,3}\.){3}\d{1,3}$' OR IP_ORIGEN ~ '^[0-9a-fA-F:]+$'),
    EXITOSO         BOOLEAN         NOT NULL DEFAULT FALSE,
    FECHA_INTENTO   TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY(ID_INTENTO)
);

--******************************
-- SEGURIDAD
--******************************

CREATE TABLE IF NOT EXISTS TOKENS_RECUPERACION
(
    ID_TOKEN        SERIAL          NOT NULL,
    EMAIL           VARCHAR         NOT NULL CHECK(EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    ID_USUARIO      VARCHAR(10)     CHECK(ID_USUARIO IS NULL OR LENGTH(ID_USUARIO) >= 6),
    ID_EMPRESA      VARCHAR(10)     CHECK(ID_EMPRESA IS NULL OR LENGTH(ID_EMPRESA) = 10),
    TOKEN           VARCHAR(64)     NOT NULL UNIQUE CHECK(LENGTH(TOKEN) = 64 AND TOKEN ~ '^[a-f0-9]{64}$'),
    FECHA_CREACION  TIMESTAMP       NOT NULL DEFAULT NOW(),
    FECHA_EXPIRA    TIMESTAMP       NOT NULL CHECK(FECHA_EXPIRA > FECHA_CREACION),
    USADO           BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(ID_TOKEN),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_PERSONA),
    FOREIGN KEY(ID_EMPRESA) REFERENCES USUARIOS_EMPRESA(ID_EMPRESA)
);

--******************************
-- RELACIONAL
--******************************

CREATE TABLE IF NOT EXISTS LIKES_RESENAS
(
    ID_RESENA    INT          NOT NULL CHECK(ID_RESENA > 0),
    ID_PERSONA   VARCHAR(10)  NOT NULL CHECK(LENGTH(ID_PERSONA) >= 6 AND ID_PERSONA ~ '^[0-9]+$'),
    FECHA_LIKE   TIMESTAMP    NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID_RESENA, ID_PERSONA),        
    FOREIGN KEY (ID_RESENA)  REFERENCES RESENAS_PLATAFORMA(ID_RESENA) ON DELETE CASCADE,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA)
);

-- Índice para contar likes rápido por reseña
CREATE INDEX IF NOT EXISTS idx_likes_resena ON LIKES_RESENAS(ID_RESENA);

-- ****************************
-- SECCIÓN DE DATOS INSERTADOS
-- ****************************

-- *********************************
-- POBLADO TABLA DE DEPARTAMENTOS
-- *********************************

INSERT INTO DEPARTAMENTOS VALUES('68','SANTANDER')
ON CONFLICT DO NOTHING;

-- ******************************
-- POBLADO TABLA DE CIUDADES
-- ******************************

INSERT INTO CIUDADES VALUES('68001','BUCARAMANGA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68013','AGUADA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68020','ALBANIA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68051','ARATOCA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68077','BARBOSA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68079','BARICHARA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68081','BARRANCABERMEJA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68092','BETULIA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68101','BOLÍVAR','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68121','CABRERA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68132','CALIFORNIA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68147','CAPITANEJO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68152','CARCASÍ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68160','CEPITÁ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68162','CERRITO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68167','CHARALÁ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68169','CHARTA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68176','CHIMA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68179','CHIPATÁ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68190','CIMITARRA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68207','CONCEPCIÓN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68209','CONFINES','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68211','CONTRATACIÓN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68217','COROMORO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68229','CURITÍ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68235','EL CARMEN DE CHUCURÍ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68245','EL GUACAMAYO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68250','EL PEÑÓN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68255','EL PLAYÓN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68264','ENCINO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68266','ENCISO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68271','FLORIÁN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68276','FLORIDABLANCA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68296','GALÁN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68298','GAMBITA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68307','GIRÓN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68318','GUACA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68320','GUADALUPE','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68322','GUAPOTÁ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68324','GUAVATÁ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68327','GÜEPSA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68344','HATO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68368','JESÚS MARÍA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68370','JORDÁN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68377','LA BELLEZA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68385','LANDÁZURI','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68397','LA PAZ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68406','LEBRIJA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68418','LOS SANTOS','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68425','MACARAVITA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68432','MÁLAGA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68444','MATANZA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68464','MOGOTES','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68468','MOLAGAVITA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68498','OCAMONTE','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68500','OIBA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68502','ONZAGA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68522','PALMAR','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68524','PALMAS DEL SOCORRO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68533','PÁRAMO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68547','PIEDECUESTA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68549','PINCHOTE','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68572','PUENTE NACIONAL','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68573','PUERTO PARRA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68575','PUERTO WILCHES','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68615','RIONEGRO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68655','SABANA DE TORRES','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68669','SAN ANDRÉS','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68673','SAN BENITO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68679','SAN GIL','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68682','SAN JOAQUÍN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68684','SAN JOSÉ DE MIRANDA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68686','SAN MIGUEL','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68689','SAN VICENTE DE CHUCURÍ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68705','SANTA BÁRBARA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68720','SANTA HELENA DEL OPÓN','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68745','SIMACOTA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68755','SOCORRO','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68770','SUAITA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68773','SUCRE','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68780','SURATÁ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68820','TONA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68842','VALLE DE SAN JOSÉ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68855','VÉLEZ','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68861','VETAS','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68867','VILLANUEVA','68')
ON CONFLICT DO NOTHING;
INSERT INTO CIUDADES VALUES('68872','ZAPATOCA','68')
ON CONFLICT DO NOTHING;

-- *************************************
-- POBLADO TABLA DE TIPOS DE DOCUMENTO
-- *************************************

INSERT INTO TIPOS_DOCUMENTOS VALUES(1, 'CEDULA DE CIUDADANIA')
ON CONFLICT DO NOTHING;
INSERT INTO TIPOS_DOCUMENTOS VALUES(2, 'CEDULA DE EXTRANJERIA')
ON CONFLICT DO NOTHING;

-- *****************************
-- POBLADO TABLA DE ALERGIAS
-- *****************************

INSERT INTO ALERGIAS VALUES(0,'NO APLICA')
ON CONFLICT DO NOTHING;
INSERT INTO ALERGIAS VALUES(1,'RINITIS ALERGICA')
ON CONFLICT DO NOTHING;
INSERT INTO ALERGIAS VALUES(2,'RINOREA')
ON CONFLICT DO NOTHING;
INSERT INTO ALERGIAS VALUES(3,'CONJUNTIVITIS ALERGICA')
ON CONFLICT DO NOTHING;
INSERT INTO ALERGIAS VALUES(4,'ASMA ALERGICA')
ON CONFLICT DO NOTHING;
INSERT INTO ALERGIAS VALUES(5,'DERMATITIS ATÓTICA')
ON CONFLICT DO NOTHING;
INSERT INTO ALERGIAS VALUES(6,'URTICARIA')
ON CONFLICT DO NOTHING;
INSERT INTO ALERGIAS VALUES(7,'DERMATITIS POR CONTACTO')
ON CONFLICT DO NOTHING;
INSERT INTO ALERGIAS VALUES(8,'ALIMENTICIA')
ON CONFLICT DO NOTHING;

-- ****************************
-- POBLADO TABLA DE PERSONAS
-- ****************************

INSERT INTO PERSONAS VALUES('1011123456', 1, 'ANA', 'GOMEZ', '3001234567', 'ANA.GOMEZ.01@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1022234567', 1, 'CARLOS', 'RAMIREZ', '3012223344', 'CARLOS.RAMIREZ.05@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1066678901', 1, 'ANDRES', 'CASTRO', '3118889900', 'ANDRES.CASTRO.80@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1077789012', 1, 'SOFIA', 'VEGA', '3165554433', 'SOFIA.VEGA.58@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1111123456', 1, 'LAURA', 'GUZMAN', '3002221100', 'LAURA.GUZMAN.11@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1122234567', 1, 'DIEGO', 'ROJAS', '3137778899', 'DIEGO.ROJAS.13@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1133345678', 1, 'VALERIA', 'SIERRA', '3121113344', 'VALERIA.SIERRA.30@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1177789012', 1, 'DIANA', 'MENDEZ', '3196665544', 'DIANA.MENDEZ.15@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1188890123', 1, 'NELSON', 'SILVA', '3023332211', 'NELSON.SILVA.51@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1255567890', 1, 'NATALIA', 'PARDO', '3108887766', 'NATALIA.PARDO.70@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('5682256981', 1, 'CARLOS', 'CHAPARRO', '3174613395', 'VIAJERO@TOURISMEASY.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('0000000001', 1, 'ADMINISTRADOR', 'TOURISMEASY', '3179998877', 'ADMIN@TOURISMEASY.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1266678901', 1, 'ROBERTO', 'MOLINA', '3006665544', 'ROBERTO.MOLINA.17@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1300012345', 1, 'MARIO', 'GIRALDO', '3153456789', 'MARIO.GIRALDO.18@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1311123456', 1, 'CECILIA', 'VELEZ', '3162345678', 'CECILIA.VELEZ.82@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1322234567', 1, 'FABIAN', 'SERNA', '3178901234', 'FABIAN.SERNA.90@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1333345678', 1, 'CLARA', 'RESTREPO', '3005678901', 'CLARA.RESTREPO.92@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1400012345', 1, 'DANIEL', 'PARDO', '3159990011', 'DANIEL.PARDO.20@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1411123456', 1, 'VIVIANA', 'SERNA', '3010001122', 'VIVIANA.SERNA.24@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1422234567', 1, 'JAIRO', 'MONTES', '3175556677', 'JAIRO.MONTES.23@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1433345678', 1, 'ROSARIO', 'CANO', '3184443322', 'ROSARIO.CANO.26@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1477789012', 1, 'DANIELA', 'DUQUE', '3192221100', 'DANIELA.DUQUE.58@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1488890123', 1, 'OSCAR', 'VARGAS', '3001110099', 'OSCAR.VARGAS.59@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1555567890', 1, 'BEATRIZ', 'PARDO', '3151110099', 'BEATRIZ.PARDO.75@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1566678901', 1, 'CESAR', 'GOMEZ', '3106665544', 'CESAR.GOMEZ.77@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1577789012', 1, 'ESTEBAN', 'ROZO', '3184567890', 'ESTEBAN.ROZO.41@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('1588890123', 1, 'MONICA', 'HERRERA', '3009876543', 'MONICA.HERRERA.46@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('9900000001', 1, 'JUAN', 'PEREZ', '3100000001', 'JUAN.PEREZ.DESTINOS@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('9900000002', 1, 'MARIA', 'LOPEZ', '3100000002', 'MARIA.LOPEZ.SOLYLUNA@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('9900000003', 1, 'PEDRO', 'GARCIA', '3100000003', 'PEDRO.GARCIA.AVENTUREROS@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO PERSONAS VALUES('9900000004', 1, 'LUIS', 'MARTINEZ', '3100000004', 'LUIS.MARTINEZ.ESTELAR@MAIL.COM', 'NINGUNA', NOW())
ON CONFLICT DO NOTHING;

-- *****************************
-- POBLADO TABLA DE USUARIOS
-- *****************************

INSERT INTO USUARIOS VALUES('1011123456','viajero','ANA.GOMEZ.01@GMAIL.COM',       ENCODE(SHA256('AmoViajar-2026'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1022234567','viajero','CARLOS.RAMIREZ.05@GMAIL.COM',  ENCODE(SHA256('CafeConLeche-10'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1066678901','viajero','ANDRES.CASTRO.80@GMAIL.COM',   ENCODE(SHA256('Bucaramanga-2026'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1077789012','viajero','SOFIA.VEGA.58@GMAIL.COM',      ENCODE(SHA256('GatosYPerros+1'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1111123456','viajero','LAURA.GUZMAN.11@GMAIL.COM',    ENCODE(SHA256('Colombia-Tierra+'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1122234567','viajero','DIEGO.ROJAS.13@GMAIL.COM',     ENCODE(SHA256('ClaveSegura-99'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1133345678','viajero','VALERIA.SIERRA.30@GMAIL.COM',  ENCODE(SHA256('PizzaConPina-No'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1177789012','viajero','DIANA.MENDEZ.15@GMAIL.COM',    ENCODE(SHA256('Atardecer-2026+'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1188890123','viajero','NELSON.SILVA.51@GMAIL.COM',    ENCODE(SHA256('NelsonPro2026+'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1255567890','viajero','NATALIA.PARDO.70@GMAIL.COM',   ENCODE(SHA256('NatiViajera-22'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('5682256981','viajero','VIAJERO@TOURISMEASY.COM',     ENCODE(SHA256('Tourismeasy-Plus'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('0000000001','admin',  'ADMIN@TOURISMEASY.COM',       ENCODE(SHA256('Admin123+'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1266678901','viajero','ROBERTO.MOLINA.17@GMAIL.COM',  ENCODE(SHA256('Rmolina-888'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1300012345','viajero','MARIO.GIRALDO.18@GMAIL.COM',   ENCODE(SHA256('MarioG-Sistemas'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1311123456','viajero','CECILIA.VELEZ.82@GMAIL.COM',   ENCODE(SHA256('CeciVelez-2026'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1322234567','viajero','FABIAN.SERNA.90@GMAIL.COM',    ENCODE(SHA256('FabianSerna+SQL'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1333345678','viajero','CLARA.RESTREPO.92@GMAIL.COM',  ENCODE(SHA256('ClaraR-Plus'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1400012345','viajero','DANIEL.PARDO.20@GMAIL.COM',    ENCODE(SHA256('DanielP-Mundial'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1411123456','viajero','VIVIANA.SERNA.24@GMAIL.COM',   ENCODE(SHA256('ViviS-Linda-2026'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1422234567','viajero','JAIRO.MONTES.23@GMAIL.COM',    ENCODE(SHA256('JairoMontes-2026'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1433345678','viajero','ROSARIO.CANO.26@GMAIL.COM',    ENCODE(SHA256('RosarioC-2026'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS VALUES('1477789012','viajero','DANIELA.DUQUE.58@GMAIL.COM',   ENCODE(SHA256('DaniDuque-2026'::BYTEA), 'hex'), 'ACTIVO')
ON CONFLICT DO NOTHING;

-- *********************************
-- POBLADO TABLA DE EMPRESAS
-- *********************************

INSERT INTO EMPRESAS VALUES('9010058882','DESTINOS MAGICOS COLOMBIA S.A.S',     'INFO@DESTINOSMAGICOS.COM.CO',              '6076451122','68001','PLANES')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('8305551119','ALOJAMIENTO CAMPESTRE SOL Y LUNA LTDA','RESERVAS@SOLYLUNA.COM.CO',                 '6013214567','68547','HOSPEDAJE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9008763215','AVENTUREROS DEL CHICAMOCHA S.A.S',     'CONTACTO@AVENTUREROSCHICAMOCHA.COM.CO',    '6045551234','68679','PLANES')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('8005768234','TURISMO SOL Y CARIBE S.A.S',           'CONTACTO@TURISMOSOLYCARIBE.COM',           '6081234567','68872','PLANES')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('7028569447','VIAJES UNICOS S.A.S',                  'INFO@VIAJESUNICOS.COM.CO',                 '6059876543','68615','PLANES')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('8060001793','HOTELES DECAMERON COLOMBIA S.A.S.',    'HABEASDATA@DECAMERON.COM',                 '6012193000','68547','HOSPEDAJE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('8903040993','HOTELES ESTELAR S.A.',                 'SIEMPREESTELAR@HOTELESESTELAR.COM',        '6028823225','68679','HOSPEDAJE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9007600116','LOGÍSTICA GHL S.A.S. (GHL HOTELES)',   'PROTECCIONDATOS@GHLHOTELES.COM',           '6013139500','68276','HOSPEDAJE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9005218077','GLOBAL OPERADORA HOTELERA S.A.S.',     'NOTIFICACIONES@MOVICHHOTELS.COM',          '6014824466','68615','HOSPEDAJE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9003049409','TVHA S.A.S. BIC (ON VACATION)',        'SERVICIOALCLIENTE@ONVACATION.COM',         '6013078080','68872','HOSPEDAJE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('8002469858','ADMINISTRADORA HOTELERA DANN S.A.S.',  'HABEASDATA@HOTELESDANN.COM',               '6016461885','68872','HOSPEDAJE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('8300766573','FUNDACIÓN CARVAJAL (SECTOR SOCIAL)',   'FUNDACIONCARVAJAL@CARVAJAL.COM',           '6024880000','68406','PERSONAL_AUXILIAR')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9005218211','FADIS COLOMBIA S.A.S.',                'INFO@FADISCOLOMBIA.ORG',                   '6017943500','68705','PERSONAL_AUXILIAR')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('8002520008','FUNDACIÓN SALDARRIAGA CONCHA',         'COMUNICACIONES@SALDARRIAGACONCHA.ORG',     '6017421370','68406','PERSONAL_AUXILIAR')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9003778474','IPS SER ASISTENCIA (TRANSPORTE)',      'CONTACTO@SERASISTENCIA.CO',                '6013267562','68276','PERSONAL_AUXILIAR')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9003016211','FUNDACIÓN TOBE',                       'INFO@FUNDACIONTOBE.ORG',                   '6019204789','68001','PERSONAL_AUXILIAR')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9012345670', 'COPETRAN L.T.D.A',            		 'CONTACTO@COPETRAN.COM',            		 '6071234567','68001','TRANSPORTE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9012345671', 'TRANSPORTES REINA S.A.S',             'RESERVAS@TRANSPORTESREINA.COM',            '6077654321','68679','TRANSPORTE')
ON CONFLICT DO NOTHING;
INSERT INTO EMPRESAS VALUES('9012345672', 'COTRANSANGIL L.T.D.A.',               'SERVICIO@COTRASANGIL.COM',                 '6079876543','68547','TRANSPORTE')
ON CONFLICT DO NOTHING;

-- ***********************************
-- POBLADO TABLA DE USUARIOS_EMPRESA
-- ***********************************

-- Empresas con usuario ACTIVO (pueden operar)
INSERT INTO USUARIOS_EMPRESA VALUES('8305551119','RESERVAS@SOLYLUNA.COM.CO', ENCODE(SHA256('SolYLuna-Reserva26'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('9008763215','CONTACTO@AVENTUREROSCHICAMOCHA.COM.CO', ENCODE(SHA256('AventuraChica+2026'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('8903040993','SIEMPREESTELAR@HOTELESESTELAR.COM', ENCODE(SHA256('EstelarAdmin+26'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('8060001793','HABEASDATA@DECAMERON.COM', ENCODE(SHA256('Decameron2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
-- Empresas PERSONAL_AUXILIAR (ACTIVAS)
INSERT INTO USUARIOS_EMPRESA VALUES('8300766573','FUNDACIONCARVAJAL@CARVAJAL.COM', ENCODE(SHA256('Carvajal-2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('9005218211','INFO@FADISCOLOMBIA.ORG', ENCODE(SHA256('Fadis-2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('9003778474','CONTACTO@SERASISTENCIA.CO', ENCODE(SHA256('SerAsistencia-2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('9003016211','INFO@FUNDACIONTOBE.ORG', ENCODE(SHA256('Tobe-2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
-- Empresas TRANSPORTE (ACTIVAS)
INSERT INTO USUARIOS_EMPRESA VALUES('9012345670','CONTACTO@COPETRAN.COM', ENCODE(SHA256('Copetran2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('9012345671','RESERVAS@TRANSPORTESREINA.COM', ENCODE(SHA256('Tranrei2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('9012345672','SERVICIO@COTRASANGIL.COM', ENCODE(SHA256('Cotrasan2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;
-- Empresas con usuario PENDIENTE
INSERT INTO USUARIOS_EMPRESA VALUES('9010058882','INFO@DESTINOSMAGICOS.COM.CO', ENCODE(SHA256('DestinosM-2026+'::BYTEA), 'hex'), 'PENDIENTE', NOW())
ON CONFLICT DO NOTHING;
INSERT INTO USUARIOS_EMPRESA VALUES('8005768234','CONTACTO@TURISMOSOLYCARIBE.COM', ENCODE(SHA256('TurismoSol-2026'::BYTEA), 'hex'), 'PENDIENTE', NOW())
ON CONFLICT DO NOTHING;
-- Empresa con usuario INACTIVO
INSERT INTO USUARIOS_EMPRESA VALUES('7028569447','INFO@VIAJESUNICOS.COM.CO', ENCODE(SHA256('ViajesUnicos-2026'::BYTEA), 'hex'), 'INACTIVO', NOW())
ON CONFLICT DO NOTHING;
-- Empresa INACTIVA (PERSONAL_AUXILIAR) - Saldarriaga
INSERT INTO USUARIOS_EMPRESA VALUES('8002520008','COMUNICACIONES@SALDARRIAGACONCHA.ORG', ENCODE(SHA256('Saldarriaga-2026+'::BYTEA), 'hex'), 'ACTIVO', NOW())
ON CONFLICT DO NOTHING;

-- ********************************************
-- POBLADO TABLA DE CARGOS PERSONAL AUXILIAR
-- ********************************************

INSERT INTO CARGOS_PER_AUX VALUES(1,'ENFERMERO',1600000)
ON CONFLICT DO NOTHING;
INSERT INTO CARGOS_PER_AUX VALUES(2,'GUIA TURISTICO',1700000)
ON CONFLICT DO NOTHING;
INSERT INTO CARGOS_PER_AUX VALUES(3,'AU PAIR',1500000)
ON CONFLICT DO NOTHING;
INSERT INTO CARGOS_PER_AUX VALUES(4,'ASISTENTE TURISTICO',1500000)
ON CONFLICT DO NOTHING;
INSERT INTO CARGOS_PER_AUX VALUES(5,'INTÉRPRETE DE LENGUA DE SEÑAS',1800000)
ON CONFLICT DO NOTHING;
INSERT INTO CARGOS_PER_AUX VALUES(6,'GUÍA PARA DISCAPACIDAD VISUAL',1750000)
ON CONFLICT DO NOTHING;
INSERT INTO CARGOS_PER_AUX VALUES(7,'ASISTENTE DE MOVILIDAD REDUCIDA',1700000)
ON CONFLICT DO NOTHING;

-- ***********************************************
-- POBLADO TABLA DE TIPOS DE PLAN TURISTICOS
-- ***********************************************

INSERT INTO TIPOS_DE_PLAN_TURISTICO VALUES(1,'ECOTURISMO')
ON CONFLICT DO NOTHING;
INSERT INTO TIPOS_DE_PLAN_TURISTICO VALUES(2,'TURISMO GASTRONOMICO')
ON CONFLICT DO NOTHING;
INSERT INTO TIPOS_DE_PLAN_TURISTICO VALUES(3,'TURISMO RELIGIOSO')
ON CONFLICT DO NOTHING;
INSERT INTO TIPOS_DE_PLAN_TURISTICO VALUES(4,'TURISMO RURAL')
ON CONFLICT DO NOTHING;
INSERT INTO TIPOS_DE_PLAN_TURISTICO VALUES(5,'TURISMO AVENTURA')
ON CONFLICT DO NOTHING;
INSERT INTO TIPOS_DE_PLAN_TURISTICO VALUES(6,'TURISMO CULTURAL')
ON CONFLICT DO NOTHING;
INSERT INTO TIPOS_DE_PLAN_TURISTICO VALUES(7,'TURISMO DE SALUD Y BIENESTAR')
ON CONFLICT DO NOTHING;

-- *********************************************************************************************
-- POBLADO TABLA FESTIVIDADES_SANTANDER
-- *********************************************************************************************

INSERT INTO FESTIVIDADES_SANTANDER VALUES ('ferias_malaga','01-06','MÁLAGA • PROVINCIA GARCÍA ROVIRA','FERIAS Y FIESTAS DEL RETORNO','¡Capital de García Rovira! Fiesta taurina, comparsas y folclor caprino 🐐🎉','🐐','#009B3A','#FFCD00','#FFFFFF','#0a2311','REGIONAL','68432')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('fiestas_floridablanca','01-20','FLORIDABLANCA • TIERRA DULCE','FIESTAS DE SAN JUAN NEPOMUCENO','¡La capital mundial del dulce y la oblea está de celebración! 🥞🍯','🥞','#009B3A','#FFCD00','#FFFFFF','#1e293b','REGIONAL','68276')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('insurreccion_comunera','03-16','EL SOCORRO • CUNA DE LA LIBERTAD','INSURRECCIÓN COMUNERA','¡Manuela Beltrán rompe el edicto! El primer grito de libertad 📜🔥','📜','#D21034','#009B3A','#FFFFFF','#2d080c','REGIONAL','68755')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('santanderianidad','05-13','SANTANDER • COLOMBIA','FELIZ DÍA DE LA SANTANDERIANIDAD','¡Siempre adelante, ni un paso atrás! 🐜','🐜','#009B3A','#FFCD00','#D21034','#111827','REGIONAL','68001')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('afrocolombianidad','05-21','SANTANDER • INCLUSIVO','DÍA DE LA AFROCOLOMBIANIDAD','Celebrando la herencia, libertad y cultura afro en nuestra region 🤎🥁','🥁','#000000','#FFCD00','#009B3A','#0f0f0f','REGIONAL','68001')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('san_pedro_molagavita','06-29','MOLAGAVITA • GARCÍA ROVIRA','FIESTAS DE SAN PEDRO','¡Tierra del chivo y el porrón! Tradición y alegría en la montaña ⛰️🎻','🎻','#009B3A','#FFFFFF','#FFCD00','#0c1e12','REGIONAL','68468')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('ferias_giron','07-03','SAN JUAN DE GIRÓN • PUEBLO PATRIMONIO','FIESTAS DEL RETORNO','Celebrando la tradición colonial, el tabaco y la hojarasca 🍂⛪','⛪','#FFCD00','#D21034','#FFFFFF','#1e293b','REGIONAL','68307')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('virgen_carmen_barbosa','07-16','BARBOSA • PUERTA DE SANTANDER','FIESTAS DE LA VIRGEN DEL CARMEN','¡Festival del Río Suárez y desfile de transportadores! 🌊🚗','🌊','#D21034','#FFFFFF','#009B3A','#1e293b','REGIONAL','68077')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('independencia_colombia','07-20','CONMEMORACIÓN NACIONAL','INDEPENDENCIA DE COLOMBIA','¡Orgullo patrio! 216 años de libertad, historia y diversidad','🇨🇴','#FFCD00','#003893','#CE1126','#061630','NACIONAL',NULL)
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('batalla_boyaca','08-07','FIESTA PATRIA NACIONAL','BATALLA DE BOYACÁ','Homenaje a nuestros héroes y a la consolidación de la libertad ⚔️','🎖️','#FFCD00','#003893','#CE1126','#061630','NACIONAL',NULL)
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('festival_velez','08-08','VÉLEZ • CAPITAL DE LA GUABINA','FESTIVAL NACIONAL DE LA GUABINA Y EL TIPLE','¡Tierra del bocadillo, el traje típico y el torbellino! 🪕💃','🪕','#FFFFFF','#009B3A','#FFFFFF','#082111','REGIONAL','68855')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('ferias_zapatoca','08-16','ZAPATOCA • CIUDAD DE LEVITÁ','FERIAS Y FIESTAS DE LA CORDIALIDAD','Clima de seda, cuevas históricas y el calor de su gente 🌲🍃','🌲','#009B3A','#FFFFFF','#FFCD00','#1e293b','REGIONAL','68872')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('festival_tiple_charala','08-30','CHARALÁ • TIERRA DE PRÓCERES','FESTIVAL DEL TIPLE Y LA COMPOSICIÓN','Homenaje a la dinastía Martínez y a la libertad de la patria 🎸','🎸','#D21034','#009B3A','#FFCD00','#210508','REGIONAL','68167')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('feria_bonita','09-04','BUCARAMANGA','¡VIENE LA FERIA BONITA!','Ciudad de los Parques, la más hermosa de Colombia 🌳👑','👑','#FFCD00','#009B3A','#D21034','#1e293b','REGIONAL','68001')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('semana_santanderianidad_piedecuesta','09-15','PIEDECUESTA • TIERRA DE GARRATEROS','SEMANA DE LA PIEDECUESTANIDAD','¡Cuna del tabaco, el biche, la arcilla y el talento garrotero! 🍂🏺','🏺','#D21034','#009B3A','#D21034','#210508','REGIONAL','68547')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('festival_cine_barichara','09-20','BARICHARA • EL PUEBLITO MÁS LINDO',   'FESTIVAL DE CINE VERDE','Cine bajo las estrellas entre calles de piedra amarilla 🎬🌻','🎬','#009B3A','#FFCD00','#FFFFFF','#1e293b','REGIONAL','68079')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('ferias_san_gil','09-29','SAN GIL • CAPITAL TURÍSTICA','FERIA DEL TURISMO Y AVENTURA','Tierra del rafting, el parapente y el Río Fonce 🌊🪂','🛶','#009B3A','#FFCD00','#D21034','#1e293b','REGIONAL','68679')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('festival_retorno_barrancabermeja', '10-12','BARRANCABERMEJA • CAPITAL PETROLERA', 'FESTIVAL DE DEPORTES NÁUTICOS Y RETORNO','¡Calor humano, petróleo, ciénaga y la mejor pollera colorá! 🐠🔥','🐠','#000000','#FFCD00','#009B3A','#0f0f0f','REGIONAL','68081')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('ferias_curiti','10-16','CURITÍ • TIERRA DE TEJEDORES','FERIAS Y FIESTAS DEL FIQUE','Artesanías que tejen la historia y cultura de nuestro pueblo 🧶🌾','🧶','#009B3A','#FFCD00','#FFFFFF','#1e293b','REGIONAL','68229')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('cumpleanos_bucaramanga','11-11','BUCARAMANGA • 300+ AÑOS','CUMPLEAÑOS DE LA CIUDAD BONITA','¡Orgullo de la capital de los santandereanos! 🌳🏢','🏢','#FFCD00','#009B3A','#D21034','#1e293b','REGIONAL','68001')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('parranda_velez','12-06','PROVINCIA DE VÉLEZ','PARRANDA VELEZANA','¡A sonar los tiples, requintos y alpargatas en decembrina! 🪕🎄','🎅','#FFFFFF','#009B3A','#FFFFFF','#082111','REGIONAL','68855')
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('creacion_departamento','12-22','CONMEMORACIÓN HISTÓRICA','CREACIÓN DEL DEPARTAMENTO','¡Orgullosamente de la tierra del Cañón del Chicamocha! ⛰️','⛰️','#009B3A','#FFCD00','#D21034','#111827','NACIONAL',NULL)
ON CONFLICT DO NOTHING;
INSERT INTO FESTIVIDADES_SANTANDER VALUES ('navidad','12-24','¡FELICES FIESTAS EN FAMILIA!','¡FELIZ NAVIDAD!','Que la paz, el amor y los tamales santandereanos llenen tu hogar 🎄✨','🎄','#CE1126','#009B3A','#FFFFFF','#051f0d','NACIONAL',NULL)
ON CONFLICT DO NOTHING;

-- ***********************************
-- POBLADO TABLA RESEÑAS
-- ***********************************

DO $RESENAS_PLATAFORMA$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM RESENAS_PLATAFORMA LIMIT 1) THEN
    INSERT INTO RESENAS_PLATAFORMA (ID_RESENA, ID_PERSONA, PUNTUACION, COMENTARIO, FECHA_CREACION) VALUES
    -- Ana Gómez · Bucaramanga · 5 estrellas (Usuario con reservas 10 y 13)
    (DEFAULT, '1011123456', 5,
     'TourismEasy cambió por completo mi forma de viajar. Encontré transporte adaptado desde Bucaramanga hasta el Cañón del Chicamocha sin ningún inconveniente.',
     NOW() - INTERVAL '2 days'),
    -- Carlos Ramírez · Floridablanca · 5 estrellas (Usuario con reservas 1 y 11)
    (DEFAULT, '1022234567', 5,
     'Excelente plataforma para turismo accesible en Santander. Reservé un plan a Barichara y todo estuvo perfectamente organizado. Los guías especializados marcaron la diferencia. ¡100% recomendado!',
     NOW() - INTERVAL '5 days'),
    -- Sofía Vega · San Gil · 4 estrellas (Usuario con reserva 2)
    (DEFAULT, '1077789012', 4,
     'Muy buena experiencia reservando hospedaje accesible en San Gil. La plataforma es intuitiva y el proceso fue rápido. Le doy 4 estrellas porque me gustaría ver más opciones de planes para personas con discapacidad visual.',
     NOW() - INTERVAL '9 days'),
    -- Laura Guzmán · Girón · 5 estrellas (NO tiene reservas, pero es usuario)
    (DEFAULT, '1111123456', 5,
     'Nunca pensé que viajar con movilidad reducida pudiera ser tan fácil. Gracias a TourismEasy encontré empresas de transporte con vehículos adaptados y hoteles con habitaciones especiales en Girón. ¡Una experiencia increíble!',
     NOW() - INTERVAL '14 days'),
    -- Diego Rojas · Piedecuesta · 5 estrellas (Usuario con reserva 4)
    (DEFAULT, '1122234567', 5,
     'La mejor plataforma de turismo inclusivo que he usado. Organicé un viaje familiar a Socorro y todo fue perfecto. El soporte al cliente respondió todas mis dudas muy rápido. Santander tiene mucho por ofrecer y TourismEasy lo sabe.',
     NOW() - INTERVAL '20 days'),
    -- Valeria Sierra · Bucaramanga · 4 estrellas (NO tiene reservas, pero es usuario)
    (DEFAULT, '1133345678', 4,
     'Muy satisfecha con el servicio de personal auxiliar que contraté a través de la plataforma. El guía fue muy profesional y conocía todos los destinos accesibles de la región. Definitivamente volveré a usar TourismEasy.',
     NOW() - INTERVAL '27 days'),
    -- Diana Méndez · Floridablanca · 5 estrellas (NO tiene reservas, pero es usuario)
    (DEFAULT, '1177789012', 5,
     'TourismEasy es exactamente lo que necesitaba. Como persona con discapacidad auditiva, siempre me costaba mucho planear viajes. Aquí todo está pensado para nosotros. El viaje a Barichara fue el mejor de mi vida.',
     NOW() - INTERVAL '33 days'),
    -- Natalia Pardo · Socorro · 5 estrellas (Usuario con reserva 3)
    (DEFAULT, '1255567890', 5,
     'Increíble experiencia. Usé la plataforma para reservar un plan turístico a los Pozos Azules y el servicio superó mis expectativas. Personal amable, vehículos cómodos y atención personalizada. ¡Santander es hermoso!',
     NOW() - INTERVAL '40 days');
  END IF;
END
$RESENAS_PLATAFORMA$;

-- ***********************************
-- POBLADO TABLA SERVICIOS_HOSPEDAJE
-- ***********************************

DO $SERVICIOS_HOSPEDAJE$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SERVICIOS_HOSPEDAJE LIMIT 1) THEN
        INSERT INTO SERVICIOS_HOSPEDAJE VALUES (DEFAULT, 'Wifi de Alta Velocidad',TRUE,NOW());
		INSERT INTO SERVICIOS_HOSPEDAJE VALUES(DEFAULT,'Piscina con Vista al Mar',TRUE,NOW());  
		INSERT INTO SERVICIOS_HOSPEDAJE VALUES(DEFAULT,'Rampa de Acceso PMR',TRUE,NOW());        
		INSERT INTO SERVICIOS_HOSPEDAJE VALUES(DEFAULT,'Desayuno Continental',TRUE,NOW());      
		INSERT INTO SERVICIOS_HOSPEDAJE VALUES(DEFAULT,'Ascensor Adaptado',TRUE,NOW());        
		INSERT INTO SERVICIOS_HOSPEDAJE VALUES(DEFAULT,'Parqueadero Privado',TRUE,NOW()); 
    END IF;
END
$SERVICIOS_HOSPEDAJE$;
/*
-- ***********************************
-- POBLADO TABLA HOSPEDAJE_SERVICIOS
-- ***********************************

DO $HOSPEDAJE_SERVICIOS$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM HOSPEDAJE_SERVICIOS LIMIT 1) THEN
        INSERT INTO HOSPEDAJE_SERVICIOS VALUES (1,1);
		INSERT INTO HOSPEDAJE_SERVICIOS VALUES (2,2);   
		INSERT INTO HOSPEDAJE_SERVICIOS VALUES (3,3);        
		INSERT INTO HOSPEDAJE_SERVICIOS VALUES (4,4);      
		INSERT INTO HOSPEDAJE_SERVICIOS VALUES (5,5);       
		INSERT INTO HOSPEDAJE_SERVICIOS VALUES (6,6); 
    END IF;
END
$HOSPEDAJE_SERVICIOS$;
*/